
name: "Create latest nags"
on:
  push:
    branches:
      - uprovee

jobs:
  test:
    runs-on: buntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: die latest-tag
      uses: EndBug/latest-tag@latest
      with:
        tag-name: newst
